
import "wtypes.idl";

[
  uuid(05FE15B4-AB13-4064-A22A-1A816059B6AE),
  version(1.0)
]
library LibJNIServer
{
	importlib("stdole32.tlb");
	importlib("stdole.tlb"); 

	[ 
	  uuid(05FE15B4-AB13-4064-A22A-1A816059B6AD),
	  oleautomation 
	]
	interface IJNIServer : IUnknown
	{
		[id(1)] HRESULT CreateJavaVM([in] BSTR libPath, SAFEARRAY(BSTR) vmArgs);
		[id(2)] HRESULT DestroyJavaVM([out] long* result);
		[id(3)] HRESULT FindClass([in] BSTR name, [out] long* clazz);
		[id(4)] HRESULT NewObjectArray([in] int len, [in] long clazz, [in] long init, [out] long *array);
		[id(5)] HRESULT SetObjectArrayElement([in] long array, [in] int index, [in] long val);
		[id(6)] HRESULT NewStringUTF([in] BSTR utf, [out] long *str);
		[id(7)] HRESULT GetStaticMethodID([in] long clazz, [in] BSTR name, [in] BSTR sig, [out] long *methodID);
		[id(8)] HRESULT CallStaticVoidMethod([in] long clazz, [in] long methodID, [in] SAFEARRAY(long) args);
		[id(9)] HRESULT ExceptionOccurred([out] long *throwable);
		[id(10)] HRESULT ExceptionDescribe();
		[id(11)] HRESULT ExceptionClear();
	}

	[ 
	  uuid(05FE15B4-AB13-4064-A22A-1A816059B6AC),
	  helpstring("JNIServer object") 
	]
	coclass JNIServer
	{
		[default] interface IJNIServer;
	}
}